### GET ALL USERS
GET http://localhost:3000/api/v1/users
Accept: application/json
X-API-Key: 31UOY+zPB4qMFNBbWntF9I75+dl43RvsUmONnwy7C80=


### CREATE USER
POST http://localhost:3000/api/v1/users
Accept: application/json
Content-Type: application/json
X-API-Key: 31UOY+zPB4qMFNBbWntF9I75+dl43RvsUmONnwy7C80=

{
  "name": "User Dummy 2",
  "email": "dummy.email@gmail.com"
}


### GET USER BY ID
GET http://localhost:3000/api/v1/users/b7324f7b-8c29-440e-85b1-9ec111eb77e5
Accept: application/json
X-API-Key: 31UOY+zPB4qMFNBbWntF9I75+dl43RvsUmONnwy7C80=


### UPDATE USER BY ID
PATCH http://localhost:3000/api/v1/users/11a3b419-e2c8-489d-847a-44cc4f5463b3
Accept: application/json
Content-Type: application/json
X-API-Key: 31UOY+zPB4qMFNBbWntF9I75+dl43RvsUmONnwy7C80=

{
  "name": "Changed Dummy User"
}


### DELETE USER BY ID
DELETE http://localhost:3000/api/v1/users/11a3b419-e2c8-489d-847a-44cc4f5463b3
Accept: application/json
X-API-Key: 31UOY+zPB4qMFNBbWntF9I75+dl43RvsUmONnwy7C80=